version: '2'
services:
    klask-app:
        image: klask/klask.io
        external_links:
            - klask-postgresql:postgresql
            - klask-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/klask
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    klask-postgresql:
        extends:
            file: postgresql.yml
            service: klask-postgresql
    klask-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: klask-elasticsearch
