version: '2'
services:
    klask-elasticsearch:
        container_name: klask-elasticsearch
        image: elasticsearch:2.4.1
        volumes:
            - /tmp/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
