{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klask.fullname" . }}-frontend
  labels:
    {{- include "klask.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "klask.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "klask.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "klask.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if and .Values.securityContext .Values.securityContext.readOnlyRootFilesystem }}
      initContainers:
        - name: init-html
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          command: ['sh', '-c', 'cp -r /usr/share/nginx/html/* /html/']
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          volumeMounts:
            - name: html
              mountPath: /html
      {{- end }}
      containers:
        - name: frontend
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            - name: BACKEND_BASE_URL
              value: {{ if .Values.frontend.env.api.baseUrl }}{{ .Values.frontend.env.api.baseUrl | quote }}{{ else }}"http://{{ index .Values.ingress.hosts 0 "host" }}/api"{{ end }}
            {{- range $key, $value := .Values.frontend.env.customVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.frontend.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.frontend.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.frontend.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            {{- if and .Values.securityContext .Values.securityContext.readOnlyRootFilesystem }}
            - name: html
              mountPath: /usr/share/nginx/html
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /.cache
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if and .Values.securityContext .Values.securityContext.readOnlyRootFilesystem }}
        - name: html
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
